BulkyBookWeb/Areas/Admin/Controllers/AvailabilityController.cs
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AvailabilityController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public AvailabilityController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            IEnumerable<Availability> objAvailabilityList = _unitOfWork.Availability.GetAll();
            return View(objAvailabilityList);
        }

        //GET
        public IActionResult Create()
        {

            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Availability obj)
        {

            if (ModelState.IsValid)
            {
                _unitOfWork.Availability.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = $"Ο τύπος διαθεσιμότητας {obj.Name} δημιουργήθηκε επιτυχώς";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var availabilityFromDbFirst = _unitOfWork.Availability.GetFirstOrDefault(u => u.Id == id);

            if (availabilityFromDbFirst == null)
            {
                return NotFound();
            }

            return View(availabilityFromDbFirst);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Availability obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Availability.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = $"Ο τύπος διαθεσιμότητας {obj.Name} επεξεργάστηκε επιτυχώς";
                return RedirectToAction("Index");
            }
            return View(obj);
        }


        #region API CALLS
        //POST
        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var obj = _unitOfWork.Availability.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return Json(new { success = false, message = "Σφάλμα κατα τη διαγραφή του τύπου διαθεσιμότητας" });
            }

            _unitOfWork.Availability.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = $"Ο τύπος διαθεσιμότητας {obj.Name} διαγράφηκε";
            return Json(new { success = true, message = $"Ο τύπος διαθεσιμότητας {obj.Name} διαγράφηκε" });

        }
        #endregion
    }
}

BulkyBookWeb/Areas/Admin/Controllers/CategoryController.cs
using BulkyBook.DataAccess;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookWeb.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        
        public IActionResult Index()
        {
            IEnumerable<Category> objCategoryList = _unitOfWork.Category.GetAll();
            return View(objCategoryList);
        }

        //GET
        public IActionResult Create()
        {

            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj)
        {
            //if (obj.Name == obj.DisplayOrder.ToString())
            //{
            //    ModelState.AddModelError("name", "The DisplayOrder cannot exactly match the Name.");
            //}
            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = $"Η κατηγορία {obj.Name} δημιουργήθηκε επιτυχώς";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //var categoryFromDb = _db.Categories.Find(id);
            var categoryFromDbFirst = _unitOfWork.Category.GetFirstOrDefault(u=>u.Id==id);
            //var categoryFromDbSingle = _db.Categories.SingleOrDefault(u => u.Id == id);

            if (categoryFromDbFirst == null)
            {
                return NotFound();
            }

            return View(categoryFromDbFirst);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = $"Η κατηγορία {obj.Name} επεξεργάστηκε επιτυχώς";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //public IActionResult Delete(int? id)
        //{
        //    if (id == null || id == 0)
        //    {
        //        return NotFound();
        //    }
        //    //var categoryFromDb = _db.Categories.Find(id);
        //    var categoryFromDbFirst = _unitOfWork.Category.GetFirstOrDefault(u => u.Id == id);

        //    if (categoryFromDbFirst == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(categoryFromDbFirst);
        //}

        ////POST
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public IActionResult DeletePOST(int? id)
        //{
        //    var obj = _unitOfWork.Category.GetFirstOrDefault(u => u.Id == id);
        //    if (obj == null)
        //    {
        //        return NotFound();
        //    }

        //    _unitOfWork.Category.Remove(obj);
        //    _unitOfWork.Save();
        //    TempData["success"] = $"Η κατηγορία {obj.Name} διαγράφηκε";
        //    return RedirectToAction("Index");

        //}

        //POST
        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var obj = _unitOfWork.Category.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return Json(new { success = false, message = "Σφάλμα κατα τη διαγραφή της κατηγορίας βιβλίου" });
            }

            _unitOfWork.Category.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = $"Η κατηγορία βιβλίου {obj.Name} διαγράφηκε";
            return Json(new { success = true, message = $"Η κατηγορία βιβλίου {obj.Name} διαγράφηκε" });

        }
    }
}

BulkyBookWeb/Areas/Admin/Views/Availability/Create.cshtml
@model Availability

@{
    ViewData["Title"] = "Νεο τύπο διαθεσιμότητας";
}

<form method="post">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Νέο τύπο διαθεσιμότητας</h2>
			<hr />
		</div>
		@*<div asp-validation-summary="All"></div>*@
		<div class="mb-3">
			<label asp-for="Name"></label>
			<input asp-for="Name" class="form-control" />
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>

		<button type="submit" class="btn btn-success" >Δημιουργία</button>
		<a asp-controller="Category" asp-action="Index" class="btn btn-danger" >
			Ακύρωση
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

BulkyBookWeb/Areas/Admin/Views/Availability/Delete.cshtml
@model Category

<form method="post" asp-action="Delete">
	<input asp-for="Id" hidden />
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Διαγραφή κατηγορίας</h2>
			<hr />
		</div>
		<div class="mb-3">
			<label asp-for="Name"></label>
			<input asp-for="Name" disabled class="form-control" />
		</div>
		<div class="mb-3">
			<label asp-for="DisplayOrder"></label>
			<input asp-for="DisplayOrder" disabled class="form-control" />
		</div>
		<button type="submit" class="btn btn-danger">Διαγραφή</button>
		<a asp-controller="Category" asp-action="Index" class="btn btn-secondary" >
			Ακύρωση
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

BulkyBookWeb/Areas/Admin/Views/Availability/Edit.cshtml
@model Category

@{
    ViewData["Title"] = "Επεξεργασία";
}

<form method="post">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Επεξεργασία κατηγορίας</h2>
			<hr />
		</div>
		@*<div asp-validation-summary="All"></div>*@
		<div class="mb-3">
			<label asp-for="Name"></label>
			<input asp-for="Name" class="form-control" />
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="DisplayOrder"></label>
			<input asp-for="DisplayOrder" class="form-control" />
			<span asp-validation-for="DisplayOrder" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-success" >Αποθήκευση</button>
		<a asp-controller="Category" asp-action="Index" class="btn btn-danger" >
			Ακύρωση
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

BulkyBookWeb/Areas/Admin/Views/Availability/Index.cshtml
@model IEnumerable<Availability>

@{
    ViewData["Title"] = "Διαθεσιμότητα";
}



<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Διαθεσιμότητα</h2>
		</div>
        <div class="col-6 text-end">
            <a asp-controller="Availability" asp-action="Create" class="btn btn-primary">
               <i class="bi bi-plus-circle"></i> &nbsp; Προσθήκη τύπου διαθεσιμότητας
			</a>
		</div>
	</div>
    <br /><br />
<table class="table table-striped" >
    <thead>
        <tr>
            <th>
                Διαθεσιμότητα
            </th>
            <th>
                Επεξεργασία
            </th>
            <th>
                Διαγραφή
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td width="90%">
                    @obj.Name
                </td>
                <td width="5%">

                    <a asp-controller="Availability" asp-action="Edit" asp-route-id="@obj.Id"
                        class="btn btn-primary mx-2"> <i class="bi bi-pencil-square"></i></a>
                </td>
                <td width="5%">
                    @*<button type="submit" onClick=Delete('/Admin/Availability/Delete/@obj.Id') class="btn btn-danger">Διαγραφή</button>*@
                    <a onClick=Delete('/Admin/Availability/Delete/@obj.Id')
                        class="btn btn-danger mx-2"> <i class="bi bi-trash-fill"></i></a>
                </td>
            </tr>
        }
    </tbody>


</table>
</div>


@section Scripts{
	@{
    <partial name="_ValidationScriptsPartial" />
	}

<script>

        function Delete(url) {
        Swal.fire({
            title: 'ΔΙΑΓΡΑΦΗ',
            text: 'Είστε σίγουροι οτι θέλετε να διαγράψετε την εγγραφή;',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            cancelButtonText: 'Όχι',
            confirmButtonText: 'Ναί'
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({
                    url: url,
                    type: 'DELETE',
                    success: function (data) {
                        if (data.success) {
                            location.reload();
                        }
                        else {
                            toastr.error(data.message);
                        }
                    }
                })
            }
        })
    }
</script>
}